version: '3.9'
name: postgresql_for_everyone
services:
  db:
    image: postgres:15.1
    restart: always
    env_file:
      - .env
    volumes:
      - type: volume
        source: pgsql
        target: /var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432

volumes:
  pgsql:
